# Requirements:
# - Docker
builds:
    -   id: cloudflare-zero-trust-operator
        main: ./main.go
        binary: cloudflare-zero-trust-operator
        env:
            - CGO_ENABLED=0
        ldflags: "-s -w -X main.version={{ .Version }} -X main.commitHash={{ .ShortCommit }} -X main.buildDate={{ .Date }}"
        goos:
            - linux
            - darwin
        goarch:
            - amd64
            - arm64
archives:
    -   id: cloudflare-zero-trust-operator
        name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
        builds:
            - cloudflare-zero-trust-operator
        format_overrides:
            - goos: windows
              format: zip

checksum:
    name_template: "checksum.txt"

changelog:
    skip: false