resources:
  - manager.yaml

images:
  - name: controller
    newName: ghcr.io/bojanzelic/cloudflare-zero-trust-operator
    newTag: 0.1.7
# secretGenerator:
#   - name: cloudflare-creds
#     literals:
#       - CLOUDFLARE_API_KEY=""
#       - CLOUDFLARE_API_EMAIL=""
#       - CLOUDFLARE_ACCOUNT_ID=""