apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-f-zero-trust-operator-leader-election-role
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bojanzelic-cloudflare-zero-trust-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: bojanzelic-cloudflare-zero-trust-operator
  {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-f-zero-trust-operator-leader-election-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bojanzelic-cloudflare-zero-trust-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: bojanzelic-cloudflare-zero-trust-operator
  {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "cloudflare-zero-trust-operator.fullname" . }}-f-zero-trust-operator-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cloudflare-zero-trust-operator.fullname" . }}-f-zero-trust-operator-controller-manager'
  namespace: '{{ .Release.Namespace }}'