apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-leader-election-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessapplications/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessgroups/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare-zero-trust-operator.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}

  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare-zero-trust-operator.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}

  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare-zero-trust-operator.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
