apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-zero-trust-operator.fullname" . }}-creds
  labels:
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
data:
  CLOUDFLARE_API_EMAIL: {{ default "" .Values.cloudflare_api_email | b64enc | quote }}
  CLOUDFLARE_ACCOUNT_ID: {{ default "" .Values.cloudflare_account_id | b64enc | quote }}
  CLOUDFLARE_API_KEY: {{ default "" .Values.cloudflare_api_key | b64enc | quote }}
