# permissions for end users to view cloudflareservicetokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudflareservicetoken-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bojanzelic-cloudflare-zero-trust-operator
    app.kubernetes.io/part-of: bojanzelic-cloudflare-zero-trust-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflareservicetoken-viewer-role
rules:
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens/status
  verbs:
  - get
