---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessapplications/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessgroups/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareaccessgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.zelic.io
  resources:
  - cloudflareservicetokens/status
  verbs:
  - get
  - patch
  - update
