apiVersion: cloudflare.zelic.io/v4alpha1
kind: CloudflareAccessApplication
metadata:
  name: domain-example
  annotations:
    cloudflare.zelic.io/prevent-destroy: "true"
spec:
  name: my application
  domain: example.cf-operator-tests.uk
  policies: 
    - name: Allow testemail1
      decision: allow
      include:
        - emails:
          - testemail1@domain.com