apiVersion: cloudflare.kadaan.info/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: domain-example
  annotations:
    cloudflare.kadaan.info/prevent-destroy: "true"
spec:
  name: my application
  domain: example.cf-operator-tests.uk
  policies: 
    - name: Allow testemail1
      decision: allow
      include:
        - emails:
          - testemail1@domain.com