name: Build Image
on:
  push:
    # branches:
    #   - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
env:
  PLATFORMS: linux/amd64,linux/arm64
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Determine tag or commit
        uses: haya14busa/action-cond@v1
        id: refortag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: latest
      - name: Determine image tag
        id: imagetag
        run: echo "::set-output name=value::${TAG_OR_BRANCH##*/}"
        env:
          TAG_OR_BRANCH: ${{ steps.refortag.outputs.value }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build cloudflare-zero-trust-operator
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/bojanzelic/cloudflare-zero-trust-operator:${{ steps.imagetag.outputs.value }}
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache