name: Integration Tests
on:
  pull_request:
  pull_request_target:
    types: [labeled]
  push:
    branches:
      - 'main'
    tags:
      - '*'
      
concurrency: 
  group: integration_tests
  cancel-in-progress: false
  
jobs:
  integration-tests:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test'))
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
    - name: Checkout Repository
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3
    - name: Checkout Repository PR
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.0'
    - run: make integration-test
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
