name: Integration Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.0'
    - run: make integration-test