name: Integration Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    concurrency: integration_tests
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.0'
    - run: make integration-test
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}