name: Integration Tests
on:
  pull_request_target:
    types:
      - labeled
      - synchronize
    branches:
      - main
  push:
    branches:
      - 'main'
    tags:
      - '*'
      
concurrency: 
  group: integration_tests
  
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
    - name: Checkout Repository
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Checkout Repository PR
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 2
        ref: "refs/pull/${{ github.event.number }}/merge"
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - run: make integration-test
      if: github.event_name == 'push' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test'))
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    - name: Upload coverage to Codecov
      if: github.event_name == 'pull_request_target'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        override_pr: ${{ github.event.number }}
        override_commit: ${{ github.event.pull_request.head.sha }}
    - name: Upload coverage to Codecov
      if: github.event_name != 'pull_request_target'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
