name: Perform Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token with elevated perms
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.AUTOMERGE_APP_ID }}
          private_key: ${{ secrets.AUTOMERGE_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'
      - name: Update version
        run: |
          # Helm version
          yq e -i '.version = "${{ github.event.inputs.tag }}"' helm/cloudflare-zero-trust-operator/Chart.yaml
          yq e -i '.appVersion = "${{ github.event.inputs.tag }}"' helm/cloudflare-zero-trust-operator/Chart.yaml
          
          # Version in README.md
          sed -i.bak -e '/<!-- Version_Placeholder -->/ {' -e 'n; s|.*|![Version: ${{ github.event.inputs.tag }}](https://img.shields.io/badge/Version-${{ github.event.inputs.tag }}-informational?style=flat-square)|' -e '}' README.md && rm README.md.bak
          
          # Build Manifests
          make manifests
          # Build Helm chart
          make helm
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          tag: ${{ github.event.inputs.tag }}