name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - run: make test